### ISSUE TITLE
Add support to vertical scrolling

### ISSUE THREAD

**Issue by JonSnow1077** [aleksanderwozniak/table_calendar#552] opened 2021-07-21 14:15 UTC
Please kindly add vertical support! If there is support, Can someone please tell me how to do it?

```
 return TableCalendar(
      focusedDay: DateTime.now(),
      firstDay: DateTime(2021, 1, 1),
      lastDay: DateTime(2021, 12, 31),
      headerVisible: false,
      calendarFormat: CalendarFormat.month,
    );
```

**Comment by aleksanderwozniak** [comment] 2021-07-24 08:58
Closing as this is a duplicate of #232; updates will be posted there.

**Closed by aleksanderwozniak** 2021-07-24 08:58 UTC
