### ISSUE TITLE
Error: Required named parameter 'vsync' must be provided.

### ISSUE THREAD

**Issue by qwkings** [aleksanderwozniak/table_calendar#685] opened 2022-04-14 06:43 UTC
version:
    table_calendar: ^3.0.5

![Snipaste_2022-04-14_14-39-38](https://user-images.githubusercontent.com/101852047/163328683-41b0f756-8aeb-46c6-b918-80f5db3202e9.png)

**Comment by aleksanderwozniak** [comment] 2022-05-04 09:00
Duplicate of #665

**Closed by aleksanderwozniak** 2022-05-04 09:00 UTC
Labels: bug
