### ISSUE TITLE
Decoration error

### ISSUE THREAD

**Issue by shubham-shukla1** [aleksanderwozniak/table_calendar#816] opened 2023-08-17 11:21 UTC
**Describe the bug**

1. Select range dates  and long press in between selected dates and then tap on any in between selected dates

**Screens

https://github.com/aleksanderwozniak/table_calendar/assets/45933756/ebf049a8-3a6c-440f-8d8c-40c08fb993c6

**Output of `flutter doctor`**
════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/painting/box_decoration.dart': Failed assertion: line 130 pos 12: 'shape != BoxShape.circle || borderRadius == null': is not true.
box_decoration.dart:130
The relevant error-causing widget was
TableCalendar<dynamic>

**Comment by aleksanderwozniak** [comment] 2024-03-24 12:45
Looks like duplicate of https://github.com/aleksanderwozniak/table_calendar/issues/583

**Closed by aleksanderwozniak** 2024-03-24 12:45 UTC
Labels: bug
