### ISSUE TITLE
How to make today's list automatically show on the screen instead of tap the day to show it? 

### ISSUE THREAD

**Issue by lutang123** [aleksanderwozniak/table_calendar#278] opened 2020-06-21 04:27 UTC
Hi, I have been working a lot trying to figure out how to use Table Calendar, right not I can add list or event to the calendar and on each day it will show dots, but everytime when I first open the calendar screen, it only show a calendar with dots below the date, but not showing the list, only if I tap on the day, it will show. Here is part of the code:
onDaySelected: (date, events) {
                            setState(() {
                              _selectedList = _selectedDayEvents;
                            });
                          },
And I can see today is the initial selectedDay, so today should be selected, but I can not automatically see today's list unless I tap on it. Is it designed this way? is there way to change? 

Any help is appreciated, Thank you!

Lu

**Comment by Renaud404** [comment] 2020-07-03 15:09
Hello,
Probably not the best solution but it works (im new in flutter since some days and had the same issue with async data), you can 'force' to show today's list in the initState, if you call a setState to refresh the _selectedEvents with the date of today  :

// INSIDE initState()
      setState(() {
        var maintenant = DateTime.now();
        if(_events[maintenant ] != null){ // to avoid an error if no event today
          _selectedEvents = _events[ladatemm];
        }
      });

**Comment by lutang123** [comment] 2020-07-03 23:38
Thank you so much, but still it's the same problem when user first come to the calendar page, it's only a calendar with dots under the date, they have to tap on the date to see the list, which I don't think is the best UI, e.g. Google Calendar, you will always see today's list on the top when you open the calendar, and of course you can also tap on other date to see other day's list. 

Another problem with this _selectedEvents (which is a List<dynamic> for each day's events, We can only assign a value when we tap on the date, and then we setState to change the UI, but if we use firebase or other backend database storage, and when user add a new item on a certain day, user will not be able to see the newly-added item immediately, they can only see the update when they tap again on the date, because this _selectedList can only show new list when user tap on it. Am I making myself clear here? 

What I want to do is very simple, just like a todo list app, user can add new item on a chosen day and it will show on calendar too, and I use Firebase Cloud Firestore to store data, and then use a StreamBuilder to retrieve data. I am able to make the data show on calendar, but it only shows the dots below each day, you can tap to see each day's list, but if user add a new item, they will not see it immediately(user may think they didn't add successfully), they can only see the update if they tap again on the date. I have been struggling with this calendar for several weeks, it's so far the best calendar option on flutter based on my research, but I don't know is it not designed well or I am not doing correctly. There're very few real-world examples I can learn to apply. Is anyone can share insight on this, any help could appreciate. 

thank you very much!

Lu

**Comment by chitgoks** [comment] 2020-07-05 06:00
came across this. related in a way since i also want the list for today's date to show instead of waiting for the user to click.

currently i do not see any way possible. this looks like an internal upgrade.

hoping the author will take notice and add this feature.

**Comment by Renaud404** [comment] 2020-07-05 15:22
you have to put all the events at the same Time of the DateTime to see them (witch is obviously bad but it works..) 

@lutang123 , when you add an event, call again the SetState with _selectedEvents  and you will see the new event without tap

**Comment by CassieLiu0916** [comment] 2020-08-07 02:17
@Renaud404 Could you please elaborate on the use of setState? I encounter a similar problem when trying to display a new event immediately after the user adds it. I use SQLite to store data and an AlertDialog is shown for users to add a new event. Below is part of code.

```
 Future<void> _showAddDialog() async {
    DateTime _pickedDay = _calendarController.selectedDay;
    String _eventDetail;
    await showDialog<void>(
      context: context,
      barrierDismissible: false,
      builder: (BuildContext context) => StatefulBuilder(
        builder: (BuildContext context, StateSetter setState) => AlertDialog(
          title: Center(child: Text('Add event')),
          content: SingleChildScrollView(
            child: Container(
              height: 200,
              child: Form(
                key: _formKey,
                child: Column(
                  children: <Widget>[
                    const SizedBox(
                      height: 5.0,
                    ),
                    TextFormField(
                      minLines: 1,
                      maxLines: 4,
                      controller: _eventController,
                      decoration: InputDecoration(
                        border: OutlineInputBorder(),
                        labelText: 'Event detail',
                      ),
                      validator: (String value) =>
                          value.isEmpty ? 'Please enter event detail.' : null,
                    ),
                    const SizedBox(
                      height: 5.0,
                    ),
                    ListTile(
                      title: Text("Date (YYYY - MM - DD)"),
                      subtitle: Text(
                          "${_pickedDay.year} - ${_pickedDay.month} - ${_pickedDay.day}"),
                      onTap: () async {
                        DateTime _picked = await showDatePicker(
                            context: context,
                            initialDate: _calendarController.selectedDay,
                            firstDate: DateTime(
                                _calendarController.selectedDay.year - 5),
                            lastDate: DateTime(
                                _calendarController.selectedDay.year + 5));

                        if (_picked != null)
                          setState(() => _pickedDay = _picked);
                      },
                    ),
                  ],
                ),
              ),
            ),
          ),
          actions: <Widget>[
            FlatButton(
                child: Text('Cancel'),
                onPressed: () {
                  _eventController.clear();
                  Navigator.pop(context);
                }),
            FlatButton(
              child: Text("Save"),
              onPressed: () async {
                if (_formKey.currentState.validate()) {
                  _eventDetail = _eventController.text;
                  await _db.insertEvent(
                      Event(_pickedDay, _eventDetail));
                  setState(() => _events.update(
                        _pickedDay,
                        (previousEvents) => previousEvents..add(_eventDetail),
                        ifAbsent: () => [_eventDetail],
                      ));
                  _eventController.clear();
                  Navigator.pop(context);
                }
              },
            ),
          ],
        ),
      ),
    );
  }
```

**Comment by aleksanderwozniak** [comment] 2020-12-10 14:23
Hi, do you mean an event list below the TableCalendar, like here?

![Image](https://raw.githubusercontent.com/aleksanderwozniak/table_calendar/assets/table_calendar_styles.gif)

This is a separate widget. To control it, lift the state up (above both TableCalendar and the ListView). 
`initialSelectedDay` is controlled by you, same as `events` that are passed to the calendar. This means you will know beforehand which events should be visible in the list below. Check this part of [example project](https://github.com/aleksanderwozniak/table_calendar/blob/b839da162d2d94e03e0e5e5604315477b11fc86d/example/lib/main.dart):
https://github.com/aleksanderwozniak/table_calendar/blob/b839da162d2d94e03e0e5e5604315477b11fc86d/example/lib/main.dart#L108

**Comment by lutang123** [comment] 2020-12-29 06:59
Thank you for everyone's response! 

Sorry for the late reply, I didn't know I got replies until now. I will check more frequently in the future.

@aleksanderwozniak Yes, I mean events like those below the calendar. I checked your example, basically you are give value to events and _selectedEvents from initialState method. This works, but in my case I have events coming from firebase as a stream, and I used StreamBuilder and assign value to events, like this:

builder: (context, snapshot) {
        if (snapshot.hasData) {
          final List<Todo> todos = snapshot.data;
          if (todos.isNotEmpty) {
            _events = DailyTodosDetails.getEvents(
                todos); //return a map to use on calender
            
            ///not working
            // final _selectedDay = DateTime.now();
            // _selectedEvents = _events[_selectedDay] ?? [];
            // print('selectedEvents: $_selectedEvents'); // []

I have value in  _events, but the _selectedList is always empty.

I have tried my best to explore many features that Table calendar can provide and I used it to create my app iMomentum Productivity App, it's published in both Android and iOS store. 

The method I used is different, it's a bit complicated and not perfect. I basically get _todayEvents separated from _selectedEvents. Because the initial value of _selectedEvents is empty, so in the UI I say if _selectedEvents isEmpty, show _todayEvents, otherwise show _selectedEvents. it works, but the downside is when no events on this day and you tap on it, it always show _todayEvents. I am not sure how to fix yet. If you have any hint, please let me know. 

Anyway, a big thanks for you to create Table Calendar, it's awesome. And thanks for all who replied me to trying to help.

**Comment by aleksanderwozniak** [comment] 2021-01-07 14:33
@lutang123 
I have a suspicion that `_events` contain DateTimes with time-part. If your `_selectedDay` has a different time-part than those, using `[]` operator sadly won't work, since it compares each segment of two DateTimes.

What you can do, is wrap `_events` with `LinkedHashMap`. Here is an [example](https://github.com/aleksanderwozniak/table_calendar/blob/e7d4f34783e47e89d86bc4b289f39ddbefc66c14/example/lib/pages/simple_example.dart#L22) how to do it. This will overwrite default `[]` behavior - allowing you to compare dates just by their years, months and days (that is without the time-part).

Once your `_selectedEvents` list is not empty when it shouldn't be, I think things will work as intended.

**Comment by herman-the-worm** [comment] 2021-02-03 21:13
I still think that the current design goes against the "grain" of how BLoC is setup.

Why would you usually retrieve any data in the init state function? I am not an expert in flutter, but running the get request directly in the init state does not make things like it is supposed to be.

Is there a way to trigger 'setState' to load _selectedEvents on the DateTime.now()? 

Did anyone found a good workaround besides .init function data retrieval to _selectedEvents?

**Comment by herman-the-worm** [comment] 2021-02-03 21:13
@aleksanderwozniak

**Comment by aleksanderwozniak** [comment] 2021-02-03 21:44
@herman-the-worm 
The things is that events are something that you put inside the calendar - meaning that you have full control over them. You can easily get events associated with any date, because they are linked together beforehand.

To get the `selectedEvents` on `DateTime.now()` you don't even need the calendar, since you control the data in question. You have the "event base" which you can use to retrieve a list of events, and you have the date (`DateTime.now()`) that you want the events for. If you are using a map, it is as simple as calling `events[date]` - but note that DateTime object compare using their time component as well, which is why I suggested using a `LinkedHashMap` in https://github.com/aleksanderwozniak/table_calendar/issues/278#issuecomment-756152924.

Essentially, calendar provides you just with a date that user selected. Now that you have that date, you can call the "event base" yourself to get the `selectedEvents`. This is actually one of the changes I'm introducing in v3.0.0 - `onDaySelected` callback will no longer provide the selectedEvents, since they can be acquired manually if needed:

https://github.com/aleksanderwozniak/table_calendar/blob/8f6f47c6006105c8f2e53c615847f136c2d0abb3/example/lib/pages/table_events_example.dart#L62

There is nothing wrong with requesting data in `initState()` - see https://stackoverflow.com/questions/52249578/how-to-deal-with-unwanted-widget-build/52249579#52249579. In case of this issue, loading `selectedEvents` in `initState()` isn't a must, it's just a way of saying that you don't need to wait for `onDaySelected` callback to get those initial events. For example, you could do the same in the initial state of your BLoC.

**Comment by herman-the-worm** [comment] 2021-02-03 22:01
Thanks for clarifying and @aleksanderwozniak a swift response.

I will try following your advice. I think it should work just fine now

Thanks

**Comment by aleksanderwozniak** [comment] 2021-02-19 13:06
Closing this for now, but feel free to ask further if needed.

**Closed by aleksanderwozniak** 2021-02-19 13:06 UTC

**Comment by herman-the-worm** [comment] 2021-04-08 15:15
Another workaround that I have found is to re-create a DateTime object before it arrives to the calendarWidget and to eliminate time differences and it works as well. But LinkedHashMap is definitely a cleaner solution
