### ISSUE TITLE
TableCalendar in SingleChildScrollView Not Working

### ISSUE THREAD

**Issue by hpsolver** [aleksanderwozniak/table_calendar#729] opened 2022-08-26 04:49 UTC
**Describe the bug**

**To reproduce**
Please include a short code sample that can be used to reproduce the problem.
<details>
<summary>Code sample</summary>
</details>

**Expected behavior**

**Screenshots**

**Output of `flutter doctor`**
Paste the result of this command here.
<details>
<summary>Output</summary>
</details>

**Additional context**

**Comment by aleksanderwozniak** [comment] 2022-10-30 15:48
Duplicate of https://github.com/aleksanderwozniak/table_calendar/issues/648

**Closed by aleksanderwozniak** 2022-10-30 15:48 UTC
Labels: bug
