### ISSUE TITLE
Multi-color event

### ISSUE THREAD

**Issue by ederluca** [aleksanderwozniak/table_calendar#249] opened 2020-05-02 23:47 UTC
Good evening everyone

I would like to clarify a doubt to each event of mine in the description of it I have a variable that would be the type of the event, Holiday ('H'), Delivery ('D') and I needed that when it was a Holiday type event the same stay on the date and a red mark and when it was a delivery it was marked blue is it possible to do that?

Checking the source of the plugin, I located the _buildMarker widget and found that it would be there where I could change the color but I would have to change the font. How can I customize the markers?

**Comment by aleksanderwozniak** [comment] 2020-05-07 21:02
Duplicate of #183

**Closed by aleksanderwozniak** 2020-05-07 21:02 UTC
