### ISSUE TITLE
Next/Prev Increments

### ISSUE THREAD

**Issue by byronferguson** [aleksanderwozniak/table_calendar#17] opened 2019-03-22 18:32 UTC
The current 2-week view increments a single week at a time; however I feel that is odd behavior. Both the single week and single month views give you an entirely need set of dates to view; whereas, the "bottom" week becomes the "top" week in the 2-week view.

I feel like the increment/step behavior should match the current displayed duration. Thus it would move forward, or backwards, two weeks at a time.

**Comment by aleksanderwozniak** [comment] 2019-03-23 08:33
Yes, that is correct. 

This is intended behavior - it allows the end user to see _currentWeek_ and  _previousWeek/nextWeek_ at the same time, no matter the setup. While I agree that jumping by two weeks feels better, it disturbs the concept mentioned above, as sometimes it would be _previousWeek_ with _currentWeek_, and other times it would be _currentWeek_ with _nextWeek_ (but never both).

However, if you still think two week increments are better suited for your use case, feel free to post a PR, preferably with some option to choose between those two configs.

**Comment by pauldemarco** [comment] 2019-09-14 21:53
It does feel a little weird since the animation looks like it slides the 2 weeks out to the left, and a new 2 weeks comes in from the right.
Perhaps if the animation instead slid up or down, to show that the week is still around.

**Comment by aleksanderwozniak** [comment] 2019-09-22 14:55
@pauldemarco 
That's an idea I had a while ago, but it raises another issue -> **Table Calendar** already uses vertical sliding to change between calendar formats (e.g. from month-view to week-view), and mixing behavior like this is bad UX.

I'll probably provide an option to select the desired increment.

**Comment by newit-quanph** [comment] 2020-03-20 04:36
@aleksanderwozniak 
Is there any option to change the way for increment yet? 
I am seeking for a solution of vertical infinite scrolling calendar

**Comment by shamilovtim** [comment] 2020-05-04 16:18
One solution that will scale across all different interval types is to have some way of processing an array of ranges: `calendar: [{start-end}, {start-end}, {start-end}]`. In this way the increment will be whatever range someone decides. Of course that requires a significant refactor to all of the way the formats are handled because currently that are locked from currentday+30 or currentday+7 rather than functioning based on ranges.

**Comment by aleksanderwozniak** [comment] 2021-02-02 19:41
Ultimately I decided to make two-week increments the default implementation in `3.0.0`, as it does feel more natural to use. Closing, since this solves the issue.

**Closed by aleksanderwozniak** 2021-02-02 19:41 UTC
