### ISSUE TITLE
Getting this error when BoxShape is Rectangle "shape != BoxShape.circle || borderRadius == null"

### ISSUE THREAD

**Issue by nehal076** [aleksanderwozniak/table_calendar#605] opened 2021-10-27 13:12 UTC
```
rangeStartDecoration: const BoxDecoration(
  shape: BoxShape.rectangle,
  borderRadius: BorderRadius.all(Radius.circular(10)),
  color: ZeplinColors.blue_violet_dark,
),
rangeEndDecoration: const BoxDecoration(
  shape: BoxShape.rectangle,
  borderRadius: BorderRadius.all(Radius.circular(10)),
  color: ZeplinColors.blue_violet_dark,
),
```

`'package:flutter/src/painting/box_decoration.dart': Failed assertion: line 131 pos 12: 'shape != BoxShape.circle || borderRadius == null': is not true.`

I want to have this. But it glitches.

<img src="https://user-images.githubusercontent.com/32421196/139072544-c89db107-4144-4ba2-a2ec-e8159aa21ffb.png" height=400>

This may be happening because of the following lines where you have hardcoded `BoxShape.circle` -- 

![image](https://user-images.githubusercontent.com/32421196/139073657-0e4e4225-9af5-45d8-99bc-a98306eaed18.png)

**Comment by aleksanderwozniak** [comment] 2021-11-03 08:47
You need to change other decorations to `BoxShape.rectangle` as well. Closing as a duplicate of https://github.com/aleksanderwozniak/table_calendar/issues/583.

**Closed by aleksanderwozniak** 2021-11-03 08:47 UTC
