### ISSUE TITLE
Calendar slide animation slow

### ISSUE THREAD

**Issue by jmsandamil** [aleksanderwozniak/table_calendar#145] opened 2019-10-30 11:42 UTC
Hello

when I add many events to the calendar the animation of changing the month becomes very slow,

If I add 20 or 30 in different months is ok, but if I add every days is slow. I need add to every days .

this is my _buildEventsMarker:

`Widget _buildMarksMarker(DateTime date, List marks) {
    return Container(
      decoration: BoxDecoration(
          shape: BoxShape.circle, color: HexColor(marks[0].color),
      ),
      width: 25.0,
      height: 20.0,
      child: Center(
        child: Text(marks[0].title[0].toUpperCase()),
      ),
    );
  }`

I get events from sqlite database after save a list of events

**Comment by jmsandamil** [comment] 2019-10-31 14:59
or how I can disable animation ?

**Comment by aleksanderwozniak** [comment] 2019-11-01 11:07
Can you provide a fully working sample, so that I can reproduce the issue?

**Comment by jmsandamil** [comment] 2019-11-03 15:19
how I can events in every days in 5 or 6 years without share all my app?

in may app when I put 20 or 30 events month change animation is ok, but when I put events in every days in some years, when I change month is slowly.

**Comment by bilaloz** [comment] 2019-11-07 11:16
or how I can disable animation ? maybe

**Comment by jmsandamil** [comment] 2019-11-07 12:47
> or how I can disable animation ? maybe

Yes, is posible?

**Comment by aleksanderwozniak** [comment] 2019-11-08 07:16
Currently the horizontal slide animation cannot be directly disabled. However, you can disable the horizontal swipe gesture, which will do 2 things:
* horizontal swipe won't be detected; you will need to use header buttons to get to previous/next month
* slide animation will be disabled

To do that, use
```dart
availableGestures: AvailableGestures.verticalSwipe,
```

or

```dart
availableGestures: AvailableGestures.none,
```

Additionally, I plan to change current slide behavior -> for further reference check #55.

___

@jmsandamil 
Are you loading data to all those months at once, or are you supplying it on demand? If you load events only for the currently visible month, and then load again when month is changed, the performance should be better - try using `onVisibleDaysChanged` callback, if you aren't already.

**Comment by jmsandamil** [comment] 2019-11-08 09:14
I charge the events for the entire calendar at the start of the application, in  onVisibleDaysChanged I don't know how to do what you tell me¡¡¡

**Comment by aleksanderwozniak** [comment] 2019-11-08 10:26
Let's say you have 10k entries split into 5 years. To display the events for currently visible month, you don't need those 10k entries inside Calendar -> you just need a much smaller subset. 

Now, `onVisibleDaysChanged` gets triggered whenever you:
a) change the current month
b) change `CalendarFormat` (for example go from month-view to week-view)

`onVisibleDaysChanged` gives you 3 params:

- `first` -> the first `DateTime` on currently visible date range
- `last` -> the last `DateTime` on currently visible date range
- `format` -> the current `CalendarFormat`

You can use this information to fetch only the events that are needed for current date range, however using `calendarController.focusedDay` will be a bit simpler, so let's go with that.

```dart
onVisibleDaysChanged: (first, last, format) {
  final visibleMonth = _calendarController.focusedDay.month;
  final visibleYear = _calendarController.focusedDay.year;

  final newEvents = repository.fetchEvents(year: visibleYear, month: visibleMonth);

  setState(() {
    _events = newEvents;
  });
},
```

Now you just need to implement `repository.fetchEvents`, which:
* takes in current year and month
* requests data from sqflite database for only the given year and month
* returns that data in a format that is proper for TableCalendar: Map<DateTime, List>

**Comment by jmsandamil** [comment] 2019-11-10 17:04
https://youtu.be/FA20fjkhsr8
https://youtu.be/6FIaruSyYUk

**Comment by aleksanderwozniak** [comment] 2019-11-11 15:02
Yes, I am aware :)
Like I said, I already work on improving it. 

Since this issue seems to be solved with `onVisibleDaysChanged`, I'm closing it. If you want to follow updates on animation improvement, head on to #55.

**Closed by aleksanderwozniak** 2019-11-11 15:02 UTC
