### ISSUE TITLE
Not show dynamic list event

### ISSUE THREAD

**Issue by javico2609** [aleksanderwozniak/table_calendar#111] opened 2019-09-17 20:29 UTC
Inside Stream, Bloc, Redux, Provider builder not render the new map events.

```
 StoreConnector<AppState, MyCalendarViewModel>(
        distinct: true,
        converter: (store) => MyCalendarViewModel.fromStore(store),
        builder: (_, vm) {
          return  TableCalendar(
                locale: vm.locale.toString(),
                calendarController: _calendarController,
                events: vm.currentEvents,
         );
}):
```

**Comment by aleksanderwozniak** [comment] 2019-09-22 14:47
Duplicate of #86.

**Closed by aleksanderwozniak** 2019-09-22 14:47 UTC

**Comment by ricardogobbo** [comment] 2021-07-02 23:03
Any clue how can I do this with table_calendar ^3.x?
