### ISSUE TITLE
pre-select a day

### ISSUE THREAD

**Issue by riobijanero** [aleksanderwozniak/table_calendar#103] opened 2019-09-02 09:04 UTC
thank you for this great plugin.
when I render this calender, I have to press "today" to see the available events for that day. 
is there a possibility to have a certain day selected and see the available events by default when I render the calendar?

**Comment by aleksanderwozniak** [comment] 2019-09-06 19:19
Duplicate of #90

**Closed by aleksanderwozniak** 2019-09-06 19:19 UTC
