### ISSUE TITLE
Translation not available for "week" word

### ISSUE THREAD

**Issue by bilawal786** [aleksanderwozniak/table_calendar#775] opened 2023-02-22 11:32 UTC
**Describe the bug**
Translation not available for "week" word

**To reproduce**
Please include a short code sample that can be used to reproduce the problem.
<details>
<summary>Code sample</summary>
</details>

**Expected behavior**

**Screenshots**

**Output of `flutter doctor`**
Paste the result of this command here.
<details>
<summary>Output</summary>
</details>

**Additional context**

**Comment by developersatisa** [comment] 2023-07-06 13:01
I did it this way:
            .......
            locale: 'es_ES',
            availableCalendarFormats: const {
              CalendarFormat.month: 'ver mes',
              CalendarFormat.twoWeeks: 'ver 2 semanas',
              CalendarFormat.week: 'ver 1 semana'
            },
            ........

**Comment by aleksanderwozniak** [comment] 2024-02-24 14:05
Duplicate of #76

**Closed by aleksanderwozniak** 2024-02-24 14:05 UTC
Labels: bug
