### ISSUE TITLE
Bug scrolling forward when in 2 weeks mode

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [aleksanderwozniak/table_calendar#421] opened 2021-03-03 15:38 UTC
I have a clendar set for a month. 
Click on 2 weeks button
Click "Forward"
You should see that only one week scrolled forward.

If you click backwards - 2 weeks is scrolled as expected

**Comment by aleksanderwozniak** [comment] 2021-03-03 16:47
Looks like a duplicate of #17, feel free to reopen if otherwise.

**Closed by aleksanderwozniak** 2021-03-03 16:47 UTC

**Comment by vytautas-pranskunas-** [comment] 2021-03-03 17:18
But 3.0.0 is in beta right?

**Comment by aleksanderwozniak** [comment] 2021-03-04 10:54
Actually, null safety has just been added to Flutter stable, so you can now use [3.0.0](https://pub.dev/packages/table_calendar/versions/3.0.0-nullsafety.0) on stable channel as well.
