### ISSUE TITLE
Holidays not displaying

### ISSUE THREAD

**Issue by KrunchMuffin** [aleksanderwozniak/table_calendar#181] opened 2020-02-02 05:59 UTC
Hi,

I have changed the holiday years to 2020, but nothing appears when using the builder version.

```
final Map<DateTime, List> _holidays = {
  DateTime(2020, 1, 1): ['New Year\'s Day'],
  DateTime(2020, 1, 6): ['Epiphany'],
  DateTime(2020, 2, 14): ['Valentine\'s Day'],
  DateTime(2020, 4, 21): ['Easter Sunday'],
  DateTime(2020, 4, 22): ['Easter Monday'],
};
```

```
  Widget _buildHolidaysMarker() {
    return Icon(
      Icons.cake,
      size: 20.0,
      color: Colors.lightGreenAccent,
    );
  }
```

![image](https://user-images.githubusercontent.com/1037197/73603914-1ed57b80-4557-11ea-85ee-dd29341b5ace.png)

**Comment by aleksanderwozniak** [comment] 2020-02-05 18:27
Did those holidays appear in months from year 2019? Or are they not rendering at all?

Just tried it myself and holiday markers seem to be working correctly for both non-builder and builder versions. Note that you need to hot-restart instead of hot-reloading.

**Comment by KrunchMuffin** [comment] 2020-02-05 18:35
Hi,

Not sure what you mean on the first line? Feb 14th is always valentines day. This is what is in the example main.dart.

```
// Example holidays
final Map<DateTime, List> _holidays = {
  DateTime(2019, 1, 1): ['New Year\'s Day'],
  DateTime(2019, 1, 6): ['Epiphany'],
  DateTime(2019, 2, 14): ['Valentine\'s Day'],
  DateTime(2019, 4, 21): ['Easter Sunday'],
  DateTime(2019, 4, 22): ['Easter Monday'],
};
```

all I did was change to `2020`

I did do full restart many times during testing.
I haven't been back to it since. If it's working for you, I must have messed something up  that doesn't cause an error.

**Comment by aleksanderwozniak** [comment] 2020-02-05 19:08
My understanding is that after you changed the year from `2019` to `2020`, you didn't see the holiday markers in any month belonging to year `2020`. Now the question is if those markers do not render at all, or they do render, but in 'old' `DateTime`, i.e. year `2019`.

**Comment by KrunchMuffin** [comment] 2020-02-05 19:38
They do not render at all as shown in the image for the 14th.

**Comment by aleksanderwozniak** [comment] 2020-02-05 19:47
Your image shows just the February of **2020**. Does the February of **2019** also struggle with rendering? I am asking specifically for February **2019**, since that is the year that was previously used in `DateTime` setup.

**Comment by KrunchMuffin** [comment] 2020-02-05 19:51
That I haven't tried yet. I will do that and let you know.

**Comment by zyllus17** [comment] 2020-02-10 13:42
I am facing the same issue. I changed the years to 2020 and the color turned blue for 14 Feb as mentioned. But in the events container, I want to display the reason of the Holiday. Instead of events on particular days, when I press on 14th Feb it should display Valentine's Day. This is what @KrunchMuffin is trying to imply. 

Can you plz guide how to achieve this...

**Comment by aleksanderwozniak** [comment] 2020-02-10 20:45
@zyllus17 
I see. I will need to add an interface to support holidays in the same way as events are treated.

**Comment by zyllus17** [comment] 2020-02-23 11:11
@aleksanderwozniak Any work around as of now to display holidays like events?

**Comment by aleksanderwozniak** [comment] 2020-02-23 11:30
Try adding this to `onDaySelected` callback:

```dart
setState(() {
  final key = DateTime(day.year, day.month, day.day);
  final selectedHolidays = _calendarController.visibleHolidays[key];
  _selectedEvents = selectedHolidays ?? events;
});
```

**Comment by zyllus17** [comment] 2020-02-26 10:32
> Try adding this to `onDaySelected` callback:
> 
> ```dart
> setState(() {
>   final key = DateTime(day.year, day.month, day.day);
>   final selectedHolidays = _calendarController.visibleHolidays[key];
>   _selectedEvents = selectedHolidays ?? events;
> });
> ```

It doesn't seem to work, however I think I have a workaround but I can't get my head around it. I was thinking of converting the `_events` list to the dates on which I want to mention the holidays, Eg.  Instead of Event A0, it will show New Year .The problem is I don't understand the subtract and add features in the events as given below-->

````
_events = {
      _selectedDay.subtract(Duration(days: 30)): [
        'Event A0',
        'Event B0',
        'Event C0'
      ],
      _selectedDay.subtract(Duration(days: 27)): ['Event A1'],
      _selectedDay.subtract(Duration(days: 20)): [
        'Event A2',
        'Event B2',
        'Event C2',
        'Event D2'
      ],
````

If you could just show a sample as to how I can get the [1,1,2020] date to show New Year in the event section, I will make the rest of it myself.

**Comment by aleksanderwozniak** [comment] 2020-02-26 19:38
If you apply my comment to example project then you have everything needed in there: when you tap on a day which is a holiday (e.g. New Year) you will see that particular holiday listed underneath the TableCalendar; if you tap on a day which is not a holiday - the event list will be displayed instead.

`add` and `subtract` are just operations on `DateTime`. They add and subtract time (`Duration`). You can easily replace them with standard `DateTime` constructor:
```dart
_events = {
    ...
    DateTime(2020, 1, 1): ['New Year'],
    ...
}
```

**Comment by zyllus17** [comment] 2020-02-26 19:57
Thank you @aleksanderwozniak  . I figured that out and completed my project.

I hope this will help @KrunchMuffin . 

https://github.com/zyllus17/Flutter-Calendar

I think you can close this thread now @aleksanderwozniak . I uploaded my prototype and I suppose it will just do the work which @KrunchMuffin was looking for.

**Comment by shaikabbas051** [comment] 2020-03-18 19:44
> Hi,
> 
> I have changed the holiday years to 2020, but nothing appears when using the builder version.
> 
> ```
> final Map<DateTime, List> _holidays = {
>   DateTime(2020, 1, 1): ['New Year\'s Day'],
>   DateTime(2020, 1, 6): ['Epiphany'],
>   DateTime(2020, 2, 14): ['Valentine\'s Day'],
>   DateTime(2020, 4, 21): ['Easter Sunday'],
>   DateTime(2020, 4, 22): ['Easter Monday'],
> };
> ```
> 
> ```
>   Widget _buildHolidaysMarker() {
>     return Icon(
>       Icons.cake,
>       size: 20.0,
>       color: Colors.lightGreenAccent,
>     );
>   }
> ```
> 
> ![image](https://user-images.githubusercontent.com/1037197/73603914-1ed57b80-4557-11ea-85ee-dd29341b5ace.png)

how did you make the weekend header style to blue colour? For me, it is red by default and I'm unable to change

**Comment by aleksanderwozniak** [comment] 2020-04-08 17:37
@shaikabbas051 
You can find this and more in the [example project](https://github.com/aleksanderwozniak/table_calendar/blob/master/example/lib/main.dart#L173):
```dart
daysOfWeekStyle: DaysOfWeekStyle(
  weekendStyle: TextStyle(color: Colors.blue),
),
```

**Closed by aleksanderwozniak** 2020-04-08 17:37 UTC
