### ISSUE TITLE
Calendar height dont change size if doesnt show the calendar

### ISSUE THREAD

**Issue by lucas-sesti** [aleksanderwozniak/table_calendar#198] opened 2020-02-20 18:01 UTC
I'm trying just have the header and remove all content of calendar like this 
![image](https://user-images.githubusercontent.com/11727165/74964186-c117af00-53f1-11ea-93ce-a7af906b199a.png), but the height it is showing yet, how can i remove??

**Comment by aleksanderwozniak** [comment] 2020-02-22 22:38
Duplicate of #196

**Closed by aleksanderwozniak** 2020-02-22 22:38 UTC
