### ISSUE TITLE
如何只滑动start 与 end 之间的月份

### ISSUE THREAD

**Issue by sanrixue** [aleksanderwozniak/table_calendar#241] opened 2020-04-23 08:42 UTC
如何只滑动start 与 end 之间的月份

**Comment by aleksanderwozniak** [comment] 2020-05-05 10:59
From Google Translate:
`如何只滑动start 与 end 之间的月份` -> `How to slide only the month between start and end`

Looks like a duplicate of #100

**Closed by aleksanderwozniak** 2020-05-05 10:59 UTC
