### ISSUE TITLE
Set state not working

### ISSUE THREAD

**Issue by vhessam** [aleksanderwozniak/table_calendar#109] opened 2019-09-12 22:01 UTC
I use _setState_ to update the calendar data by setting only __events_ map variable in my state class. But nothing happened! 
After debugging I figured out that the __events_ instance variable in __calendarController_ object kept the previous value! **(after calling setState method)** But __events_ variable in my state class takse new value! (naturally)
It's worth to know that I use a custom class in _events:
old: Map<DateTime, List>
new: Map<DateTime, List < CalendarTimeEntry > >

CalendarTimeEntry is my custom class

**Comment by aleksanderwozniak** [comment] 2019-09-21 20:10
FYI, custom class in `_events` changes absolutely nothing.

Duplicate of #86, will be resolved soon.

**Closed by aleksanderwozniak** 2019-09-21 20:10 UTC
