### ISSUE TITLE
iOS increased font size causes days of week to be clipped

### ISSUE THREAD

**Issue by litaoz** [aleksanderwozniak/table_calendar#802] opened 2023-06-18 01:30 UTC
**Describe the bug**
Increased font size in iOS causes the days of weeks header to have the bottom parts cut off.

**To reproduce**
Please include a short code sample that can be used to reproduce the problem.
<details>
<summary>Code sample for Calendar widget usage</summary>

```
final kToday = DateTime.now();

TableCalendar(
    focusedDay: kToday,
    firstDay: DateTime(kToday.year, kToday.month, 1),
    lastDay: DateTime(kToday.year, kToday.month + 1, 1).add(const Duration(days: -1)),
 )
```
</details>

1. In iOS simulator (I used iPhone 14 Pro Max), Setting > Accessibility > Display & Text Size > Larger Text, increase text size
2. Open app with Calendar widget

**Expected behavior**
The header row with the days of the week should increase in height, not cut off the text.

**Screenshots**
<img src="https://github.com/aleksanderwozniak/table_calendar/assets/6503022/07d09492-4175-4d1b-9db2-49032b71f1ed" src="Simulator Screenshot - iPhone 14 Pro Max - 2023-06-17 at 20 54 35" alt= “” width="30%" height="30%">

**Comment by NemoTheHero** [comment] 2023-07-20 04:04
Ah that's what was happening! I was wondering why my emulator was different from my phone! +1

**Comment by PisaIlogs** [comment] 2023-10-03 09:18
This is also happening in our Android apps, when increasing the font size via the Android settings. +1

**Comment by LGCDualboot** [comment] 2024-03-18 17:47
+1

**Comment by aleksanderwozniak** [comment] 2024-03-24 13:59
Duplicate of #713. Check out https://github.com/aleksanderwozniak/table_calendar/issues/713#issuecomment-1180699391 for a workaround

**Closed by aleksanderwozniak** 2024-03-24 13:59 UTC
Labels: bug
