### ISSUE TITLE
The following assertion was thrown building AnimatedContainer(duration: 250ms, Alignment.center, padding: EdgeInsets.zero, bg: BoxDecoration(color: Color(0xff6262d5), borderRadius: BorderRadius.circular(10.0)), margin: EdgeInsets.all(6.0), clipBehavior: Clip.none, dirty, state: _AnimatedContainerState#d3f3a(ticker active, AlignmentGeometryTween(Alignment.center → Alignment.center), padding: EdgeInsetsGeometryTween(EdgeInsets.zero → EdgeInsets.zero), bg: DecorationTween(BoxDecoration(shape: circle) → BoxDecoration(color: Color(0xff6262d5), borderRadius: BorderRadius.circular(10.0))), margin: EdgeInsetsGeometryTween(EdgeInsets.all(6.0) → EdgeInsets.all(6.0)))): 'package:flutter/src/painting/box_decoration.dart': Failed assertion: line 128 pos 12: 'shape != BoxShape.circle || borderRadius == null': is not true.

### ISSUE THREAD

**Issue by ShiyanaSam** [aleksanderwozniak/table_calendar#852] opened 2024-01-29 11:38 UTC
**Describe the bug**

**To reproduce**
Please include a short code sample that can be used to reproduce the problem.
  TableCalendar(
                          
                          calendarStyle: CalendarStyle(
                            todayTextStyle: AppTextStyles.n14w600.black,
                            todayDecoration:
                                const BoxDecoration(borderRadius: null),

                            rangeHighlightColor: AppColors.progressBackground,
                            rangeStartTextStyle: AppTextStyles.n14w600.white,
                            rangeEndTextStyle: AppTextStyles.n14w600.white,
                            rangeStartDecoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(10),
                              color: AppColors.primaryLightPurple,
                      
                            ),
                            rangeEndDecoration: BoxDecoration(
                              color: AppColors.primaryLightPurple,
                              borderRadius: BorderRadius.circular(10),
                            ),
                          ),
                          rowHeight: 40,
                          currentDay: DateTime.now(),
                          focusedDay: DateTime.now(),
                          firstDay: DateTime(2000),
                          lastDay: DateTime.now(),
               
                          onFormatChanged: (format) {
                
                          },
                          onPageChanged: (focusedDay) {
                            _focusedDay = focusedDay;
                          },
                          rangeEndDay: _rangeEnd,
                          rangeStartDay: _rangeStart,
                          rangeSelectionMode: RangeSelectionMode.toggledOn,
                          onRangeSelected: _onRangeSelected,
                          headerStyle: HeaderStyle(
                            titleCentered: true,
                            titleTextStyle: AppTextStyles.n16w700,
                            formatButtonVisible: false,
                          ),
                          daysOfWeekStyle: DaysOfWeekStyle(
                            weekdayStyle: AppTextStyles.n12w700.primaryPurple,
                            weekendStyle: AppTextStyles.n12w700.primaryPurple,
                          ),
                        ),

**Expected behavior**

**Screenshots**

**Output of `flutter doctor`**
Paste the result of this command here.
The following assertion was thrown building AnimatedContainer(duration: 250ms, Alignment.center, padding: EdgeInsets.zero, bg: BoxDecoration(color: Color(0xff6262d5), borderRadius: BorderRadius.circular(10.0)), margin: EdgeInsets.all(6.0), clipBehavior: Clip.none, dirty, state: _AnimatedContainerState#d3f3a(ticker active, AlignmentGeometryTween(Alignment.center → Alignment.center), padding: EdgeInsetsGeometryTween(EdgeInsets.zero → EdgeInsets.zero), bg: DecorationTween(BoxDecoration(shape: circle) → BoxDecoration(color: Color(0xff6262d5), borderRadius: BorderRadius.circular(10.0))), margin: EdgeInsetsGeometryTween(EdgeInsets.all(6.0) → EdgeInsets.all(6.0)))): 'package:flutter/src/painting/box_decoration.dart': Failed assertion: line 128 pos 12: 'shape != BoxShape.circle || borderRadius == null': is not true.

**Additional context**

**Comment by zhangjinhuang** [comment] 2024-02-05 10:17
you need to set all decoration

**Comment by aleksanderwozniak** [comment] 2024-03-24 12:45
Looks like duplicate of https://github.com/aleksanderwozniak/table_calendar/issues/583

**Closed by aleksanderwozniak** 2024-03-24 12:45 UTC
Labels: bug
