### ISSUE TITLE
Every time you switch to the second page, it is white

### ISSUE THREAD

**Issue by gaojuanjuan** [aleksanderwozniak/table_calendar#166] opened 2019-12-24 07:20 UTC

**Comment by aleksanderwozniak** [comment] 2019-12-31 11:06
Can you provide some more details? Do you mean switching to the next month?

**Comment by neestell** [comment] 2020-01-23 10:52
@aleksanderwozniak The same issue. if I switch to the next month next page is white. You can see it on your gifs in readme

**Comment by aleksanderwozniak** [comment] 2020-01-26 19:50
@neestell Not sure if this was meant by the author, but if that's the case, then this is a duplicate of #55. Closing for now. 

@gaojuanjuan feel free to reopen if you had something else in mind.

**Closed by aleksanderwozniak** 2020-01-26 19:50 UTC
