### ISSUE TITLE
Displaying  events from stream on launch

### ISSUE THREAD

**Issue by doodatales** [aleksanderwozniak/table_calendar#416] opened 2021-02-27 20:04 UTC
I'm having trouble displaying events automatically on launch when the events are pulled from a stream in the main build widget.  In the example app, the _selectedDay is initiated to today (DateTime.now()), and "today"'s events are automatically pulled since the events are hard coded.  However when the events are pulled in from a stream, no events are displayed until you click on a date, including today's date.  Any advice on this?

**Comment by aleksanderwozniak** [comment] 2021-02-27 20:20
Sounds like a duplicate of #278, feel free to reopen if otherwise.

**Closed by aleksanderwozniak** 2021-02-27 20:20 UTC

**Comment by doodatales** [comment] 2021-02-27 20:34
Thanks so much, don't know how I missed that.
